### ISSUE TITLE
[Feature request] Compatibility with WooCommerce Price Based on Country

### ISSUE THREAD

**Issue by JurekSIN** [dcurasi/dc-moafw#1]
Hello, 

Thanks for making this awesome extension :)

I run into a small problem. I use another extension for displaying exchange rates, and the plugin doesn't see it. If I require 20 PLN, it will make customer spend 20 EUR. Do you think you would have the time to make it work with exchange rates :)?

Exchange rate plugin in question: https://wordpress.org/plugins/woocommerce-product-price-based-on-countries/screenshots/

Thanks :)

**Comment by dcurasi** [comment]
Hi,

I added compatibility for WooCommerce Price Based on Country in the new version.
Updates the plugin.

dcurasi

**Comment by JurekSIN** [comment]
Amazing!! Thank you <3

**Comment by JurekSIN** [comment]
Hey Dario!

I hope u r well and doing great this summer :)

Thank you for all your work on your tremendous plugins :) 

I didn't want to hassle you outside of support tickets, but after a while I figured I'll ask by email. Is there a chance you will update the minimum order price plugin with WPML multi currency support? That would be kickass :).

Best regards,
Jurek 

Dnia 12.03.2017 o godz. 16:33 Dario Curasì <notifications@github.com> napisał(a):
