### ISSUE TITLE
Using own html to show message on Cart page

### ISSUE THREAD

**Issue by HobbytronicsPK** [dcurasi/dc-moafw#2]
Hi. Thank you so much for such a nice plugin. It's working flawlessly with my website. I have a request from you.

Can I use my own html to display message? If so, in which file and where I have to put my html code to match the this plugin notification with other notifications of my website?

**Comment by dcurasi** [comment]
Hi,

This plugin uses the standard function for Woocommerce "wc_add_notice" notifications.
You can change this or insert your own function instead (for example, calling a add_action "woocommerce_before_cart_table").
This must be done in "dc_moafw_set_minimum_order" function in the class-dc-moafw-public.php file.
I suggest the first option.

If you like the plugin, please give it a rating.

dcurasi
