### ISSUE TITLE
Showing notice on shop Page

### ISSUE THREAD

**Issue by GaboDot** [dcurasi/dc-moafw#3]
Nice plugin, and it works very well.
So, I have a client who wants to show this notice of minimum amount but in shop page also, so the user can see the minimum order since they're adding items to cart.
How can I do this? Is there any shortcode to be called?

**Comment by dcurasi** [comment]
Hi,
it's a good idea. I will add this feature in the next update.
If you like the plugin, please give it a rating or donate for it.

dcurasi

**Comment by dcurasi** [comment]
Hi,
I have add the feature in the new version.
Updates the plugin.
If you like the plugin, please give it a rating or donate for it.

dcurasi
