### ISSUE TITLE
Number formats should use Woo's currency options

### ISSUE THREAD

**Issue by PeterBeckley** [dcurasi/dc-moafw#5]
number_format in class_dc_moafw_public.php are hard-coded against the currency format selections already set within WooCommerce.

The plugin ignores already configured decimal and thousand separators as well as currency symbol positioning. This creates a (visual and minor) conflict with currency displays for the plugin's output vs the rest of a shop.

**Comment by PeterBeckley** [comment]
Just following up with more info, it looks like using wc_price($minimum_cart_total) instead of number_format($minimum_cart_total, 2, ',', '.') pulls the currency settings from woocommerce. I'm not much of a programmer so I did that much, but can't figure out how to get the other currency symbol/text to go away now lol.

**Comment by dcurasi** [comment]
Hi PeterBeckley,

thanks for your report, i have updated the plugin.
With this update the decimal and thousands separators, the currency position and the number of decimals in the price will be automatically set as in the Woocommerce settings.

If you like the plugin, please give it a rating.

Regards,
dcurasi
